language: csharp
solution: ./malud/unity.sln
git:
  submodules: false
env:
  matrix:
    - MONO_VERSION="3.5.0"
before_install:
    - "npm install unity-solution -g"
    - "unitysolution ./malud/ugb-source"